name: beatbox_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  spotify: ^0.13.7
  http: ^1.2.2
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.3.5
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4
  cupertino_icons: ^1.0.8
  app_links: ^3.4.1
  encrypt: ^5.0.1
  flutter_secure_storage: ^8.1.0
  json_annotation: ^4.9.0
  pdf: ^3.10.4
  csv: ^5.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.3


flutter:
  assets:
    - .env
  uses-material-design: true